nginx:
    image: ibbd/nginx
    ports:
        - "80:80"
    links:
        - "php-fpm"
    volumes:
        - /etc/nginx/sites-enabled:/etc/nginx/sites-enabled
        - /var/log/nginx:/var/log/nginx 
        - /home/code/ibbd:/var/www

php-fpm:
    image: ibbd/php-fpm
    ports:
        - "9000:9000"
    links:
        - "mongo"
        - "redis"
    volumes:
        - /home/code/ibbd:/var/www
        - /var/log/php:/var/log/php

redis:
    image: ibbd/redis
    ports:
        - "6379:6379"
    volumes:
        - /data/redis:/var/lib/redis
        - /var/log/redis:/var/log/redis

mongo:
    image: ibbd/mongo
    ports:
        - "27071:27071"
    volumes:
        - /data/mongo:/var/lib/mongodb
        - /var/log/mongo:/var/log/mongodb

